#!/bin/bash

if [ $1 == "socat" ]; then
    echo "sudo socat TCP4-LISTEN:80,fork TCP4:172.16.20.72:80"
elif [ $1 == "netalias" ]; then
    echo "ifconfig enp3s0:1 172.16.20.1 netmask 255.255.0.0 up"
fi