#!/bin/bash

int_ethernet=enp3s0
int_wifi=wlo1

# ifconfig enp3s0:1 172.16.20.1 netmask 255.255.0.0 up

if [ -z "$1" ]; then
    echo "No ip"
else
    interfaces=$(netstat -i | sed 's/\|/ /'|awk '{print $1}' | grep $int_ethernet)
    ultima=$(netstat -i | sed 's/\|/ /'|awk '{print $1}' | grep $int_ethernet | tail -n 1)
    echo "Interfaces ethernet identificadas: "
    echo $interfaces

    if [ $ultima == $int_ethernet ]; then
        x=0
    else
        n=$(perl -E 'say for split quotemeta shift, shift' -- ":" "$ultima" | tail -n 1)
        x=$(echo $n+1 | bc)
    fi

    echo "Último alias: $ultima, creando $int_ethernet:$x"

    if [ -z "$2" ]; then
        echo "Ejecutando ifconfig $int_ethernet:$x $1 up con privilegios"
        sudo ifconfig $int_ethernet:$x $1 up
    else
        echo "Ejecutando ifconfig $int_ethernet:$x $1 netmask $2 up con privilegios"
        sudo ifconfig $int_ethernet:$x $1 netmask $2 up
    fi
fi